name: Shiny Semantic Unit Tests

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint shiny_semantic package
        run: black --check --line-length=100 shiny_semantic
      - name: Lint examples app
        run: black --check --line-length=100 examples
      - name: Test with unittest
        run: python -m unittest discover tests
